project:
  type: website
  preview:
    port: 4200
  output-dir: ./_site

website:
  title: "junwkim's blog"
  description: "technical writing about CS/CE"
  navbar:
    background: "#0a3e3c"
    foreground: White
    left:
      - href: pages/introduce.qmd
        text: introduce
      - href: pages/technical_writing.qmd
        text: technical writing
      - href: pages/posts.qmd
        text: posts
      - href: pages/papers.qmd
        text: papers
    right:
      - href: main.qmd
        text: Back To Home

format:
  html:
    css: styles.css
    js: script.js
